spring:
  application:
    name: eureka-client
    

  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone: http://eureka-server1:8080/eureka/
  instance:
    hostname: localhost
      
    
    
