spring:
  application:
    name: eureka-client
    
server:
  port: 8071
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone: http://eureka-server1-sample-boot-microserv.1d35.starter-us-east-1.openshiftapps.com/
  instance:
    hostname: localhost
      
    
    
